CREATE TABLE users (
  uuid UUID PRIMARY KEY,
  name VARCHAR UNIQUE NOT NULL,
  password VARCHAR NOT NULL
);

CREATE TABLE items (
  uuid UUID PRIMARY KEY,
  name VARCHAR UNIQUE NOT NULL,
  price NUMERIC NOT NULL,
  isAvailable BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE orders (
  uuid UUID PRIMARY KEY,
  user_id UUID NOT NULL,
  payment_id UUID UNIQUE NOT NULL,
  items JSONB NOT NULL,
  total NUMERIC,
  CONSTRAINT user_id_fkey FOREIGN KEY (user_id)
    REFERENCES users (uuid) MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION
);
